insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,"1969 Harley Davidson Ultimate Chopper",'https://res.cloudinary.com/db5fpphyj/image/upload/v1674572760/CapstoneImages/1969_Harley_Davidson_peeeai.jpg','This replica features working kickstand, front suspension, gear-shift lever, footbrake lever, drive chain, wheels and steering. All parts are particularly delicate due to their precise scale and require special care and attention.',7933.00,48);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1952 Alpine Renault 1300','https://res.cloudinary.com/db5fpphyj/image/upload/v1674026561/CapstoneImages/1952_Alpine_Renault_1300.jpg','Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',7305.00,98);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1996 Moto Guzzi 1100i','https://res.cloudinary.com/db5fpphyj/image/upload/v1674026951/CapstoneImages/1996_Moto_Guzzi_1100i.jpg','Official Moto Guzzi logos and insignias,working steering, working suspension, dual exhaust pipes, two-tone paint with chrome accents, superior die-cast detail,working kick stand, diecast metal with plastic parts and baked enamel finish.',6625.00,68);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'2003 Harley-Davidson Eagle Drag Bike','https://res.cloudinary.com/db5fpphyj/image/upload/v1674026992/CapstoneImages/2003_Harley_Davidson_Eagle_Drag_Bike.jpg','Features official Harley Davidson logos and insignias, separate engine drive belts, free-turning front fork, rotating tires and rear racing slick, certificate of authenticity, removable fender.',5582.00,91);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1972 Alfa Romeo GTA','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027038/CapstoneImages/1972_Alfa_Romeo_GTA.jpg','Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',3252.00,85);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1968 Ford Mustang','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027065/CapstoneImages/1968_Ford_Mustang.jpg','Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color dark green.',6485.00,95);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'2001 Ferrari Enzo','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027097/CapstoneImages/2001_Ferrari_Enzo.jpg','Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',3619.00,95);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1958 Setra Bus','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027121/CapstoneImages/1958_Setra_Bus.jpg','Model features 30 windows, skylights & glare resistant glass, working steering system, original logos',1579,'77.90');
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'2002 Suzuki XREO','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027141/CapstoneImages/2002_Suzuki_XREO.jpg','Official logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, dual exhaust pipes, small saddle bag located on handle bars, two-tone paint with chrome accents,working kick stand.',9997.00,66);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1969 Corvair Monza','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027279/CapstoneImages/1969_Corvair_Monza.jpg','1:18 scale die-cast about 10\" long doors open, hood opens, trunk opens and wheels roll',6906.00,89);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1968 Dodge Charger','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027312/CapstoneImages/1968_Dodge_Charger.jpg','1:12 scale model of a 1968 Dodge Charger. Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color black',9123.00,67);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1969 Ford Falcon','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027333/CapstoneImages/1969_Ford_Falcon.jpg','Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',1049.00,83);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1970 Plymouth Hemi Cuda','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027356/CapstoneImages/1970_Plymouth_Hemi_Cuda.jpg','Very detailed 1970 Plymouth Cuda model in 1:12 scale. The Cuda is generally accepted as one of the fastest original muscle cars from the 1970s. This model is a reproduction of one of the orginal 652 cars built in 1970. Red color.',5663.00,31);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1957 Chevy Pickup','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027426/CapstoneImages/1957_Chevy_Pickup.webp','1:12 scale die-cast about 20\" long Hood opens, Rubber wheels',6125.00,55);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1969 Dodge Charger','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027452/CapstoneImages/1969_Dodge_Charger.jpg','Detailed model of the 1969 Dodge Charger. This model includes finely detailed interior and exterior features. Painted in red and white.',7323.00,58);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1940 Ford Pickup Truck','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027471/CapstoneImages/1940_Ford_Pickup_Truck.jpg','This model features soft rubber tires, working steering, rubber mud guards, authentic Ford logos, detailed undercarriage, opening doors and hood,  removable split rear gate, full size spare mounted in bed, detailed interior with opening glove box',2613.00,58);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1993 Mazda RX-7','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027503/CapstoneImages/1993_Mazda_RX-7.jpg','This model features, opening hood, opening doors, detailed engine, rear spoiler, opening trunk, working steering, tinted windows, baked enamel finish. Color red.',3975.00,83);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1937 Lincoln Berline','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027521/CapstoneImages/1937_Lincoln_Berline.jpg','Features opening engine cover, doors, trunk, and fuel filler cap. Color black',8693.00,60);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1936 Mercedes-Benz 500K Special Roadster','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027543/CapstoneImages/1936_Mercedes_Benz_500K_Special_Roadster.jpg','This 1:18 scale replica is constructed of heavy die-cast metal and has all the features of the original: independent spring suspension, detailed interior, working steering system.',8635.00,24);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1965 Aston Martin DB5','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027582/CapstoneImages/1965_Aston_Martin_DB5.jpg','Die-cast model of the silver 1965 Aston Martin DB5 in silver. This model includes full wire wheels and doors that open with fully detailed passenger compartment. In 1:18 scale, this model measures approximately 10 inches/20 cm long.',9042.00,65);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1980s Black Hawk Helicopter','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027604/CapstoneImages/1980s_Black_Hawk_Helicopter.jpg','1:18 scale replica of actual Army\'s UH-60L BLACK HAWK Helicopter. 100% hand-assembled. Features rotating rotor blades, propeller blades and rubber wheels.',5330.00,77);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1917 Grand Touring Sedan','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027625/CapstoneImages/1917_Grand_Touring_Sedan.jpg','This 1:18 scale replica of the 1917 Grand Touring car has all the features you would expect from museum quality reproductions: detailed engine and instrument panel, chrome-look trim, all topped off with a factory baked-enamel finish.',2724.00,86);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1948 Porsche 356-A Roadster','https://carandclassic.hu/wp-content/uploads/2017/02/356-02.jpg','This precision die-cast replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare.',8826.00,53);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1995 Honda Civic','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027671/CapstoneImages/1995_Honda_Civic.jpg','This model features, opening hood, opening doors, detailed engine, rear spoiler, opening trunk, working steering, tinted windows, baked enamel finish. Color yellow.',9772.00,93);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1998 Chrysler Plymouth Prowler','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027689/CapstoneImages/1998_Chrysler_Plymouth_Prowler.jpg','Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.',4724.00,101);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1911 Ford Town Car','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027734/CapstoneImages/1911_Ford_Town_Car.jpg','Features opening hood, opening doors, opening trunk, wide white wall tires, front door arm rests, working steering system.',5407.00,33);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1964 Mercedes Tour Bus','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027770/CapstoneImages/1964_Mercedes_Tour_Bus.jpg','Exact replica. 100+ parts. working steering system, original logos',8258.00,74);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1932 Model A Ford J-Coupe','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027805/CapstoneImages/1932_Model_A_Ford_J_Coupe.jpg','This model features grille-mounted chrome horn, lift-up louvered hood, fold-down rumble seat, working steering system, chrome-covered spare, opening doors, detailed and wired engine',9354.00,58);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1926 Ford Fire Engine','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027834/CapstoneImages/1926_Ford_Fire_Engine.jpg','Gleaming red handsome appearance. Everything is here the fire hoses, ladder, axes, bells, lanterns, ready to fight any inferno.',2018.00,24);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'P-51-D Mustang','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027860/CapstoneImages/P_51_D_Mustang.jpg','Has retractable wheels and comes with a stand',99920.00,49);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1936 Harley Davidson El Knucklehead','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027886/CapstoneImages/1936_Harley_Davidson_El_Knucklehead.jpg','Intricately detailed with chrome accents and trim, official die-struck logos and baked enamel finish.',4357.00,24);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1928 Mercedes-Benz SSK','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027927/CapstoneImages/1928_Mercedes_Benz_SSK.jpg','This 1:18 replica features grille-mounted chrome horn, lift-up louvered hood, fold-down rumble seat, working steering system, chrome-covered spare, opening doors, detailed and wired engine. Color black.',5488.00,72);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1999 Indy 500 Monte Carlo SS','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027950/CapstoneImages/1999_Indy_500_Monte_Carlo_SS.jpg','Features include opening and closing doors. Color: Red',8164.00,56);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1913 Ford Model T Speedster','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027993/CapstoneImages/1913_Ford_Model_T_Speedster.jpg','This 250 part reproduction includes moving handbrakes, clutch, throttle and foot pedals, squeezable horn, detailed wired engine, removable water, gas, and oil cans, pivoting monocle windshield, all topped with a baked enamel red finish.',4189.00,60);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1934 Ford V8 Coupe','https://www.supercars.net/blog/wp-content/uploads/2016/04/1934_Ford_V81.jpg','Chrome Trim, Chrome Grille, Opening Hood, Opening Doors, Opening Trunk, Detailed Engine, Working Steering System',5649.00,34);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1999 Yamaha Speed Boat','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028034/CapstoneImages/1999_Yamaha_Speed_Boat.jpg','Exact replica. Wood and Metal. Many extras including rigging, long boats, pilot house, anchors, etc. Comes with three masts, all square-rigged.',4259.00,51);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'18th Century Vintage Horse Carriage','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028053/CapstoneImages/18th_Century_Vintage_Horse_Carriage.jpg','Hand crafted diecast-like metal horse carriage is re-created in about 1:18 scale of antique horse carriage. Features turning steering wheel and is entirely hand-finished.',5992.00,60);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1903 Ford Model A','https://myautoworld.com/ford/history/company-history/ford-model-a/1903FordModelA_08.jpg','Features opening trunk,  working steering system',3913.00,68);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1992 Ferrari 360 Spider red','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028097/CapstoneImages/1992_Ferrari%20_360_Spider_Red.jpg','his replica features opening doors, superb detail and craftsmanship, working steering system, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish.',8347.00,77);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1985 Toyota Supra','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028120/CapstoneImages/1985_Toyota_Supra.jpg','This model features soft rubber tires, working steering, rubber mud guards, authentic Ford logos, detailed undercarriage, opening doors and hood, removable split rear gate, full size spare mounted in bed, detailed interior with opening glove box',7733.00,57);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'Collectable Wooden Train','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028180/CapstoneImages/Collectable_Wooden_Train.jpg','Hand crafted wooden toy train set is in about 1:18 scale, 25 inches in total length including 2 additional carts, of actual vintage train. This antique style wooden toy train model set is all hand-assembled with 100% wood.',6450.00,67);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1969 Dodge Super Bee','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028202/CapstoneImages/1969_Dodge_Super_Bee.jpg','This replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish.',6917.00,49);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1917 Maxwell Touring Car','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028228/CapstoneImages/1917_Maxwell_Touring_Car.jpg','Features Gold Trim, Full Size Spare Tire, Chrome Trim, Chrome Grille, Opening Hood, Opening Doors, Opening Trunk, Detailed Engine, Working Steering System',7913.00,57);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1976 Ford Gran Torino','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028249/CapstoneImages/1976_Ford_Gran_Torino.jpg','Highly detailed 1976 Ford Gran Torino \"Starsky and Hutch\" diecast model. Very well constructed and painted in red and white patterns.',9127.00,73);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1948 Porsche Type 356 Roadster','https://res.cloudinary.com/db5fpphyj/image/upload/v1674027644/CapstoneImages/1948_Porsche_356_A_Roadster.jpg','This model features working front and rear suspension on accurately replicated and actuating shock absorbers as well as opening engine cover.',8990.00,62);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1957 Vespa GS150','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028293/CapstoneImages/1957_Vespa_GS150.jpg','Features rotating wheels , working kick stand. Comes with stand.',7689.00,32);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1941 Chevrolet Special Deluxe Cabriolet','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028313/CapstoneImages/1941_Chevrolet_Special_Deluxe_Cabriolet.jpg','Features opening hood, opening doors, opening trunk, wide white wall tires, front door arm rests, working steering system, leather upholstery. Color black.',2378.00,64);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1970 Triumph Spitfire','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028336/CapstoneImages/1970_Triumph_Spitfire.jpg','Features include opening and closing doors. Color: White.',5545.00,91);
insert  into product(show_product,product_name, productimg, productdesc,price_per_unit, product_qty) values
(1,'1932 Alfa Romeo 8C2300 Spider Sport','https://res.cloudinary.com/db5fpphyj/image/upload/v1674028354/CapstoneImages/1932_Alfa%20Romeo_8C2300_Spider_Sport.jpg','This 1:18 scale precision die cast replica features the 6 front headlights of the original, plus a detailed version of the 142 horsepower straight 8 engine, dual spares and their famous comprehensive dashboard. Color black.',6553.00,43);